; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = main
default_envs = freenove-esp32s3-n16r8


; #############################################################################
; Global Definitions
; Used for all environments
; #############################################################################
[env]
platform = platformio/espressif32 @ 6.11.0
framework = espidf
build_flags =
    -Wno-sign-compare
    -Wno-missing-field-initializers
    -fno-exceptions
    ;-D ENV_DISABLE_MQTT         ; Software module: Uncomment to disable
    ;-D ENV_DISABLE_INFLUXDB     ; Software module: Uncomment to disable
    ;-D ENV_DISABLE_WEBHOOK      ; Software module: Uncomment to disable
    ;-D DISABLE_POST_BUILD_TASKS ; Disable post build tasks (WebUI related tasks, etc.)
extra_scripts = post:scripts/post_build_tasks.py ; Building WebUI (tooltips, hashes, API docs, zip)
monitor_speed = 115200
monitor_filters = default, esp32_exception_decoder


; #############################################################################
; Board
; ESP32CAM
; #############################################################################
[env:esp32cam]
board = esp32cam
board_build.partitions = partitions_4MB_legacy.csv
build_flags =
    ${env.build_flags}
    -D BOARD_AITHINKER_ESP32CAM ; Define board type (see 'include/defines.h')


; #############################################################################
; Board
; XIAO ESP32S3 Sense
; #############################################################################
[env:xiao-esp32s3-sense]
board = seeed_xiao_esp32s3
board_build.partitions = partitions_8MB.csv
board_build.filesystem = fatfs
build_flags =
    ${env.build_flags}
    -D BOARD_XIAO_ESP32S3 ; Define board type (see 'include/defines.h')


; #############################################################################
; Board
; Freenove ESP32S3-WROOM-1-N8R8 (Freenove original board)
; #############################################################################
[env:freenove-esp32s3-n8r8]
board = freenove_esp32_s3_wroom
board_build.partitions = partitions_8MB.csv
board_build.filesystem = fatfs
build_flags =
    ${env.build_flags}
    -D BOARD_FREENOVE_ESP32S3_N8R8 ; Define board type (see 'include/defines.h')


; #############################################################################
; Board
; Freenove ESP32S3-WROOM-1-N16R8 (Freenove pin compatible clones)
; #############################################################################
[env:freenove-esp32s3-n16r8]
board = freenove_esp32_s3_wroom
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.partitions = partitions_16MB.csv
board_build.filesystem = fatfs
build_flags =
    ${env.build_flags}
    -D BOARD_FREENOVE_ESP32S3_N16R8 ; Define board type (see 'include/defines.h')


; #############################################################################
; Board
; Waveshare ESP32-S3-ETH
; #############################################################################
[env:waveshare-esp32s3-eth]
board = freenove_esp32_s3_wroom
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.partitions = partitions_16MB.csv
board_build.filesystem = fatfs
build_flags =
    ${env.build_flags}
    -D BOARD_WAVESHARE_ESP32S3_ETH ; Define board type (see 'include/defines.h')
