FILE(GLOB_RECURSE app_sources ${CMAKE_CURRENT_SOURCE_DIR}/*.*)

idf_component_register(SRCS ${app_sources}
                    INCLUDE_DIRS "."
                    REQUIRES esp_timer esp_wifi json tflite_ctrl misc_helper camera_ctrl mqtt_ctrl influxdb_ctrl webhook_ctrl fileserver_ota image_handling network_ctrl config_handling display)


