FILE(GLOB_RECURSE app_sources ${CMAKE_CURRENT_SOURCE_DIR}/*.*)

idf_component_register(SRCS ${app_sources}
                    INCLUDE_DIRS "." "../../include"
                    REQUIRES esp_driver_gpio esp_driver_ledc smartleds esp_http_server json logfile_handling config_handling mqtt_ctrl mainprocess_ctrl)


